name: Deploy Space A to Hugging Face
on:
  push:
    paths:
      - 'space-a/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Hugging Face Space A
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cp -r space-a/* space-a-tmp/
          cd space-a-tmp

          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Commite sur master (par d√©faut)
          git add .
          git commit -m "Deploy space-a to Hugging Face"

          # Renomme master en main
          git branch -m master main

          # Ajoute le remote HF
          git remote add hf "https://lyx51:${HF_TOKEN}@huggingface.co/spaces/lyx51/space-a"

          # Push la branche main
          git push hf main --force-with-lease
